name: bioindica
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  utm: ^0.1.2
  google_fonts: ^6.2.1
  get: ^4.6.6
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.10+1
  geolocator: ^12.0.0
  intl: 0.19.0
  liquid_pull_to_refresh: ^3.0.1
  carousel_slider: ^4.2.1
  sizer: ^2.0.15
  image_cropper: ^5.0.1
  image_picker: ^1.0.8
  dio: ^5.4.3+1
  flutter_dotenv: ^5.1.0
  lottie: ^3.1.0
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.1
  freezed: ^2.5.2
  shimmer: ^3.0.0
  equatable: ^2.0.5
  package_info_plus: ^8.0.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  json_serializable: ^6.8.0
  build_runner: ^2.4.9
  

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/custom_icons/
  fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins/Poppins-Regular.ttf
      - asset: assets/fonts/Poppins/Poppins-Medium.ttf
      - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
  - family: Inter
    fonts:
      - asset: assets/fonts/Inter/static/Inter-Regular.ttf
      - asset: assets/fonts/Inter/static/Inter-Medium.ttf
      - asset: assets/fonts/Inter/static/Inter-SemiBold.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  remove_alpha_ios: true

  